### ISSUE TITLE
Refresh Stars after click

### ISSUE THREAD

**Issue by rklaeboe** [07harish/stars-rating-react-hooks#1]
After clicking, clicked number of stars and cursor is shown.  Desired behaviour: component is reset
useState with updating of config parameters did not do the trick
Use case is  triggering  rating on containing page

**Comment by 07harish** [comment]
Hey @rklaeboe, Can you please explain by giving more details and maybe reproduce the issue on codesandbox, I will be happy to help you. Thanks.

**Comment by rklaeboe** [comment]
OK will do, and come back to you.

 

 

Kind regards

 

Ronny Klæboe dr.philos.

Department of Technology

Institute of Transport Economics 

www.toi.no

 

 

 

From: Harish Kulkarni ***@***.***>
Reply to: 07harish/stars-rating-react-hooks ***@***.***>
Date: Monday, 19 April 2021 at 19:19
To: 07harish/stars-rating-react-hooks ***@***.***>
Cc: Ronny Klæboe ***@***.***>, Mention ***@***.***>
Subject: Re: [07harish/stars-rating-react-hooks] Refresh Stars after click (#1)

 

Hey @rklaeboe, Can you please explain by giving more details and maybe reproduce the issue on codesandbox, I will be happy to help you. Thanks.
